USE [master]
GO
/****** Object:  Database [AngularWorkshop]    Script Date: 2/11/2019 2:39:40 PM ******/
CREATE DATABASE [AngularWorkshop]
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AngularWorkshop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AngularWorkshop] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AngularWorkshop] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AngularWorkshop] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AngularWorkshop] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AngularWorkshop] SET ARITHABORT OFF 
GO
ALTER DATABASE [AngularWorkshop] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AngularWorkshop] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AngularWorkshop] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AngularWorkshop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AngularWorkshop] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AngularWorkshop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AngularWorkshop] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AngularWorkshop] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AngularWorkshop] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AngularWorkshop] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AngularWorkshop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AngularWorkshop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AngularWorkshop] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AngularWorkshop] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [AngularWorkshop] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AngularWorkshop] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [AngularWorkshop] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AngularWorkshop] SET RECOVERY FULL 
GO
ALTER DATABASE [AngularWorkshop] SET  MULTI_USER 
GO
ALTER DATABASE [AngularWorkshop] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AngularWorkshop] SET DB_CHAINING OFF 
GO
USE [AngularWorkshop]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 2/11/2019 2:39:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Book](
	[Id] [int] NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[Author] [varchar](50) NOT NULL,
	[IsCheckedOut] [bit] NOT NULL,
	[Rating] [tinyint] NOT NULL,
 CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [AngularWorkshop] SET  READ_WRITE 
GO
